language: c

install:
  - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
  - sudo apt-get update
  - sudo apt-get install -y build-essential git gcc-arm-embedded

script:
  - make -C vendor/libopencm3
  - make
  - make -C firmware
  - make -C bootloader
  - make -C demo

notifications:
  webhooks:
    urls:
      - http://sway.gk2.sk:5000/travis
      - http://163.172.132.178:5000/travis
    on_success: always
    on_failure: always
    on_start: always
